#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("testQuizBazaDanych.Resource", IsApplication=true)]

namespace testQuizBazaDanych
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000f
			public const int isConvertDaysToHours = 2130771983;
			
			// aapt resource value: 0x7f010000
			public const int isHideTimeBackground = 2130771968;
			
			// aapt resource value: 0x7f01000a
			public const int isShowDay = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int isShowHour = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int isShowMillisecond = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int isShowMinute = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int isShowSecond = 2130771981;
			
			// aapt resource value: 0x7f010024
			public const int isShowTimeBgBorder = 2130772004;
			
			// aapt resource value: 0x7f010001
			public const int isShowTimeBgDivisionLine = 2130771969;
			
			// aapt resource value: 0x7f010010
			public const int isSuffixTextBold = 2130771984;
			
			// aapt resource value: 0x7f010007
			public const int isTimeTextBold = 2130771975;
			
			// aapt resource value: 0x7f010013
			public const int suffix = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int suffixDay = 2130771988;
			
			// aapt resource value: 0x7f01001b
			public const int suffixDayLeftMargin = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int suffixDayRightMargin = 2130771996;
			
			// aapt resource value: 0x7f010019
			public const int suffixGravity = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int suffixHour = 2130771989;
			
			// aapt resource value: 0x7f01001d
			public const int suffixHourLeftMargin = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int suffixHourRightMargin = 2130771998;
			
			// aapt resource value: 0x7f01001a
			public const int suffixLRMargin = 2130771994;
			
			// aapt resource value: 0x7f010018
			public const int suffixMillisecond = 2130771992;
			
			// aapt resource value: 0x7f010023
			public const int suffixMillisecondLeftMargin = 2130772003;
			
			// aapt resource value: 0x7f010016
			public const int suffixMinute = 2130771990;
			
			// aapt resource value: 0x7f01001f
			public const int suffixMinuteLeftMargin = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int suffixMinuteRightMargin = 2130772000;
			
			// aapt resource value: 0x7f010017
			public const int suffixSecond = 2130771991;
			
			// aapt resource value: 0x7f010021
			public const int suffixSecondLeftMargin = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int suffixSecondRightMargin = 2130772002;
			
			// aapt resource value: 0x7f010012
			public const int suffixTextColor = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int suffixTextSize = 2130771985;
			
			// aapt resource value: 0x7f010025
			public const int timeBgBorderColor = 2130772005;
			
			// aapt resource value: 0x7f010027
			public const int timeBgBorderRadius = 2130772007;
			
			// aapt resource value: 0x7f010026
			public const int timeBgBorderSize = 2130772006;
			
			// aapt resource value: 0x7f010004
			public const int timeBgColor = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int timeBgDivisionLineColor = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int timeBgDivisionLineSize = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int timeBgRadius = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int timeBgSize = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int timeTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int timeTextSize = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int amper = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chiny = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cpu = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int deltoid = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dwojkowy = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int everest = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ipv4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int m13B = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int nissan = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int nissaniaudi = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int p1235 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rb26 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int s13 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sekwana = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int stalagnat = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int stany = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int szesciokat = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int trojkat90 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int uklad = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int wzglednosc = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int ACtextViewNazwa = 2131034117;
			
			// aapt resource value: 0x7f05001b
			public const int answear1 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int answear2 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int answear3 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int answear4 = 2131034142;
			
			// aapt resource value: 0x7f050000
			public const int bottom = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int btnSave = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btnShow = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int buttonBack = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int buttonEasy = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int buttonExit = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int buttonHard = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int buttonLeaderboard = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int buttonMedium = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int buttonOptions = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int buttonPlay = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int center = 2131034113;
			
			// aapt resource value: 0x7f050019
			public const int imageViewQuestion = 2131034137;
			
			// aapt resource value: 0x7f050020
			public const int listViewWyborKategorii = 2131034144;
			
			// aapt resource value: 0x7f050008
			public const int listViewWyniki = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int listviewLeaderboard = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int questionsLayout = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int questionsLayout2 = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int textPunkty = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int textScored = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int textViewName = 2131034123;
			
			// aapt resource value: 0x7f05001f
			public const int textViewName1 = 2131034143;
			
			// aapt resource value: 0x7f05000c
			public const int textViewWyniki = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int textviewCzas = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int textviewPunkty = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int textviewPytanie = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int textviewZycia = 2131034134;
			
			// aapt resource value: 0x7f050002
			public const int top = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ending = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int leaderboard1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listViewKategorie = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listViewWyniki = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int optionsLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int questions = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int wyborKategorii = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CountdownView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007};
			
			// aapt resource value: 15
			public const int CountdownView_isConvertDaysToHours = 15;
			
			// aapt resource value: 0
			public const int CountdownView_isHideTimeBackground = 0;
			
			// aapt resource value: 10
			public const int CountdownView_isShowDay = 10;
			
			// aapt resource value: 11
			public const int CountdownView_isShowHour = 11;
			
			// aapt resource value: 14
			public const int CountdownView_isShowMillisecond = 14;
			
			// aapt resource value: 12
			public const int CountdownView_isShowMinute = 12;
			
			// aapt resource value: 13
			public const int CountdownView_isShowSecond = 13;
			
			// aapt resource value: 36
			public const int CountdownView_isShowTimeBgBorder = 36;
			
			// aapt resource value: 1
			public const int CountdownView_isShowTimeBgDivisionLine = 1;
			
			// aapt resource value: 16
			public const int CountdownView_isSuffixTextBold = 16;
			
			// aapt resource value: 7
			public const int CountdownView_isTimeTextBold = 7;
			
			// aapt resource value: 19
			public const int CountdownView_suffix = 19;
			
			// aapt resource value: 20
			public const int CountdownView_suffixDay = 20;
			
			// aapt resource value: 27
			public const int CountdownView_suffixDayLeftMargin = 27;
			
			// aapt resource value: 28
			public const int CountdownView_suffixDayRightMargin = 28;
			
			// aapt resource value: 25
			public const int CountdownView_suffixGravity = 25;
			
			// aapt resource value: 21
			public const int CountdownView_suffixHour = 21;
			
			// aapt resource value: 29
			public const int CountdownView_suffixHourLeftMargin = 29;
			
			// aapt resource value: 30
			public const int CountdownView_suffixHourRightMargin = 30;
			
			// aapt resource value: 26
			public const int CountdownView_suffixLRMargin = 26;
			
			// aapt resource value: 24
			public const int CountdownView_suffixMillisecond = 24;
			
			// aapt resource value: 35
			public const int CountdownView_suffixMillisecondLeftMargin = 35;
			
			// aapt resource value: 22
			public const int CountdownView_suffixMinute = 22;
			
			// aapt resource value: 31
			public const int CountdownView_suffixMinuteLeftMargin = 31;
			
			// aapt resource value: 32
			public const int CountdownView_suffixMinuteRightMargin = 32;
			
			// aapt resource value: 23
			public const int CountdownView_suffixSecond = 23;
			
			// aapt resource value: 33
			public const int CountdownView_suffixSecondLeftMargin = 33;
			
			// aapt resource value: 34
			public const int CountdownView_suffixSecondRightMargin = 34;
			
			// aapt resource value: 18
			public const int CountdownView_suffixTextColor = 18;
			
			// aapt resource value: 17
			public const int CountdownView_suffixTextSize = 17;
			
			// aapt resource value: 37
			public const int CountdownView_timeBgBorderColor = 37;
			
			// aapt resource value: 39
			public const int CountdownView_timeBgBorderRadius = 39;
			
			// aapt resource value: 38
			public const int CountdownView_timeBgBorderSize = 38;
			
			// aapt resource value: 4
			public const int CountdownView_timeBgColor = 4;
			
			// aapt resource value: 2
			public const int CountdownView_timeBgDivisionLineColor = 2;
			
			// aapt resource value: 3
			public const int CountdownView_timeBgDivisionLineSize = 3;
			
			// aapt resource value: 6
			public const int CountdownView_timeBgRadius = 6;
			
			// aapt resource value: 5
			public const int CountdownView_timeBgSize = 5;
			
			// aapt resource value: 9
			public const int CountdownView_timeTextColor = 9;
			
			// aapt resource value: 8
			public const int CountdownView_timeTextSize = 8;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
